#include "result.hpp"

// result constructor()
// result operator_at()
// result const_operator_at()
// result operator_plus_assign()
// result operator_minus_assign()
// result operator_mul_assign()
// result operator_div_assign()
// result operator_plus()
// result operator_minus()
// result operator_mul()
// result operator_div()
// result named_accessors()
// result dot()
// result cross()
// result mag()
// result sqrt_mag()
// result normalize()
